### ISSUE TITLE
Avatar component refacture

### ISSUE THREAD

**Issue by galloween** [hibobio/bob-style#492]

**Comment by raananmorag** [comment]
Avatar "Mini" need to be **36px** instead of 30px
![Screen Shot 2019-05-07 at 15 34 33](https://user-images.githubusercontent.com/48472405/57300420-72f22300-70df-11e9-82ec-d46cec9ccdff.png)
![Screen Shot 2019-05-07 at 15 42 22](https://user-images.githubusercontent.com/48472405/57300421-738ab980-70df-11e9-9871-d07615321f4c.png)

@omrihecht @doroncy 

Invision Link:
https://hibob.invisionapp.com/share/EQRVXT4C38H
https://hibob.invisionapp.com/share/DKRL544FN2U

**Comment by galloween** [comment]
avatar enum now has numbers for values, change as needed
